-- AlterEnum
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'FILE_EMPTY';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'FILE_TOO_LARGE';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'SIZE_MISMATCH';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'SIGNATURE_MISMATCH';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'PDF_INVALID';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'PDF_ENCRYPTED';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'PDF_PAGE_LIMIT_EXCEEDED';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'DOCX_INVALID';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'DOCX_ARCHIVE_LIMIT_EXCEEDED';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'DOCX_UNSAFE_PATH';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'DOCX_MACRO_UNSUPPORTED';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'MALWARE_DETECTED';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'SCANNER_UNAVAILABLE';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'SCAN_TIMEOUT';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'PROCESSING_ATTEMPTS_EXHAUSTED';

-- AlterTable
ALTER TABLE "ResumeDocument"
  ADD COLUMN "scannedCleanAt" TIMESTAMP(3),
  ADD COLUMN "processingStartedAt" TIMESTAMP(3),
  ADD COLUMN "processingLeaseToken" TEXT,
  ADD COLUMN "processingLeaseExpiresAt" TIMESTAMP(3),
  ADD COLUMN "processingAttemptCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "verificationVersion" TEXT,
  ADD COLUMN "scannerName" TEXT,
  ADD COLUMN "scannerVersion" TEXT,
  ADD COLUMN "scannerDefinitionVersion" TEXT;

-- CreateIndex
CREATE INDEX "ResumeDocument_status_processingLeaseExpiresAt_idx" ON "ResumeDocument"("status", "processingLeaseExpiresAt");
