ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'DOCLING_UNAVAILABLE';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'DOCLING_TIMEOUT';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'DOCLING_PROTOCOL_ERROR';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'DOCLING_OUTPUT_INVALID';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'DOCLING_OUTPUT_TOO_LARGE';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'OCR_FAILED';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'NO_USABLE_CONTENT';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'DOCX_IMAGE_ONLY_UNSUPPORTED';
ALTER TYPE "ResumeFailureCode" ADD VALUE IF NOT EXISTS 'EXTRACTION_ARTIFACT_WRITE_FAILED';

ALTER TABLE "ResumeParseAttempt"
  ADD COLUMN IF NOT EXISTS "artifactSha256" TEXT,
  ADD COLUMN IF NOT EXISTS "artifactByteSize" INTEGER,
  ADD COLUMN IF NOT EXISTS "artifactContentType" TEXT,
  ADD COLUMN IF NOT EXISTS "artifactCompression" TEXT;

ALTER TABLE "ResumeExtractionDraft"
  ADD COLUMN IF NOT EXISTS "extractionVersion" TEXT NOT NULL DEFAULT 'docling-contract-v1',
  ADD COLUMN IF NOT EXISTS "artifactObjectKey" TEXT,
  ADD COLUMN IF NOT EXISTS "artifactSha256" TEXT,
  ADD COLUMN IF NOT EXISTS "artifactByteSize" INTEGER,
  ADD COLUMN IF NOT EXISTS "artifactContentType" TEXT,
  ADD COLUMN IF NOT EXISTS "artifactCompression" TEXT,
  ADD COLUMN IF NOT EXISTS "warningsJson" JSONB;

CREATE INDEX IF NOT EXISTS "ResumeExtractionDraft_sourceChecksum_parserVersion_mapperVersion_idx"
  ON "ResumeExtractionDraft"("sourceChecksum", "parserVersion", "mapperVersion");
