/**
 * Canonical ISO-3166-1 Alpha-2 Registry & Allowlist
 *
 * Source standard: ISO-3166-1:2020 (ISO 3166 Maintenance Agency).
 * Covers all 249 official ISO-3166-1 alpha-2 codes plus user-assigned "XK" for Kosovo
 * (designated under ISO 3166/MA user-assigned code block, recognized by the European Commission, World Bank, and IMF).
 */

export interface CanonicalCountryRecord {
  alpha2: string;
  name: string;
}

// 249 official ISO-3166-1 alpha-2 codes + XK
export const CANONICAL_ALPHA2_SET: ReadonlySet<string> = new Set([
  "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AQ", "AR", "AS", "AT", "AU", "AW", "AX", "AZ",
  "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BL", "BM", "BN", "BO", "BQ", "BR", "BS",
  "BT", "BV", "BW", "BY", "BZ", "CA", "CC", "CD", "CF", "CG", "CH", "CI", "CK", "CL", "CM", "CN",
  "CO", "CR", "CU", "CV", "CW", "CX", "CY", "CZ", "DE", "DJ", "DK", "DM", "DO", "DZ", "EC", "EE",
  "EG", "EH", "ER", "ES", "ET", "FI", "FJ", "FK", "FM", "FO", "FR", "GA", "GB", "GD", "GE", "GF",
  "GG", "GH", "GI", "GL", "GM", "GN", "GP", "GQ", "GR", "GS", "GT", "GU", "GW", "GY", "HK", "HM",
  "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IM", "IN", "IO", "IQ", "IR", "IS", "IT", "JE", "JM",
  "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KP", "KR", "KW", "KY", "KZ", "LA", "LB", "LC",
  "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY", "MA", "MC", "MD", "ME", "MF", "MG", "MH", "MK",
  "ML", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA",
  "NC", "NE", "NF", "NG", "NI", "NL", "NO", "NP", "NR", "NU", "NZ", "OM", "PA", "PE", "PF", "PG",
  "PH", "PK", "PL", "PM", "PN", "PR", "PS", "PT", "PW", "PY", "QA", "RE", "RO", "RS", "RU", "RW",
  "SA", "SB", "SC", "SD", "SE", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SR", "SS",
  "ST", "SV", "SX", "SY", "SZ", "TC", "TD", "TF", "TG", "TH", "TJ", "TK", "TL", "TM", "TN", "TO",
  "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "UM", "US", "UY", "UZ", "VA", "VC", "VE", "VG", "VI",
  "VN", "VU", "WF", "WS", "XK", "YE", "YT", "ZA", "ZM", "ZW"
]);

// Normalized lowercase canonical name lookup -> { alpha2, canonical name }
export const CANONICAL_COUNTRIES: Record<string, CanonicalCountryRecord> = {
  "afghanistan": { alpha2: "AF", name: "Afghanistan" },
  "albania": { alpha2: "AL", name: "Albania" },
  "algeria": { alpha2: "DZ", name: "Algeria" },
  "american samoa": { alpha2: "AS", name: "American Samoa" },
  "andorra": { alpha2: "AD", name: "Andorra" },
  "angola": { alpha2: "AO", name: "Angola" },
  "anguilla": { alpha2: "AI", name: "Anguilla" },
  "antarctica": { alpha2: "AQ", name: "Antarctica" },
  "antigua and barbuda": { alpha2: "AG", name: "Antigua and Barbuda" },
  "argentina": { alpha2: "AR", name: "Argentina" },
  "armenia": { alpha2: "AM", name: "Armenia" },
  "aruba": { alpha2: "AW", name: "Aruba" },
  "australia": { alpha2: "AU", name: "Australia" },
  "austria": { alpha2: "AT", name: "Austria" },
  "azerbaijan": { alpha2: "AZ", name: "Azerbaijan" },
  "bahamas": { alpha2: "BS", name: "Bahamas" },
  "bahrain": { alpha2: "BH", name: "Bahrain" },
  "bangladesh": { alpha2: "BD", name: "Bangladesh" },
  "barbados": { alpha2: "BB", name: "Barbados" },
  "belarus": { alpha2: "BY", name: "Belarus" },
  "belgium": { alpha2: "BE", name: "Belgium" },
  "belize": { alpha2: "BZ", name: "Belize" },
  "benin": { alpha2: "BJ", name: "Benin" },
  "bermuda": { alpha2: "BM", name: "Bermuda" },
  "bhutan": { alpha2: "BT", name: "Bhutan" },
  "bolivia": { alpha2: "BO", name: "Bolivia" },
  "bosnia and herzegovina": { alpha2: "BA", name: "Bosnia and Herzegovina" },
  "botswana": { alpha2: "BW", name: "Botswana" },
  "bouvet island": { alpha2: "BV", name: "Bouvet Island" },
  "brazil": { alpha2: "BR", name: "Brazil" },
  "british indian ocean territory": { alpha2: "IO", name: "British Indian Ocean Territory" },
  "brunei darussalam": { alpha2: "BN", name: "Brunei Darussalam" },
  "brunei": { alpha2: "BN", name: "Brunei" },
  "bulgaria": { alpha2: "BG", name: "Bulgaria" },
  "burkina faso": { alpha2: "BF", name: "Burkina Faso" },
  "burundi": { alpha2: "BI", name: "Burundi" },
  "cabo verde": { alpha2: "CV", name: "Cabo Verde" },
  "cape verde": { alpha2: "CV", name: "Cabo Verde" },
  "cambodia": { alpha2: "KH", name: "Cambodia" },
  "cameroon": { alpha2: "CM", name: "Cameroon" },
  "canada": { alpha2: "CA", name: "Canada" },
  "cayman islands": { alpha2: "KY", name: "Cayman Islands" },
  "central african republic": { alpha2: "CF", name: "Central African Republic" },
  "chad": { alpha2: "TD", name: "Chad" },
  "chile": { alpha2: "CL", name: "Chile" },
  "china": { alpha2: "CN", name: "China" },
  "christmas island": { alpha2: "CX", name: "Christmas Island" },
  "cocos (keeling) islands": { alpha2: "CC", name: "Cocos (Keeling) Islands" },
  "colombia": { alpha2: "CO", name: "Colombia" },
  "comoros": { alpha2: "KM", name: "Comoros" },
  "congo": { alpha2: "CG", name: "Congo" },
  "democratic republic of the congo": { alpha2: "CD", name: "Democratic Republic of the Congo" },
  "cook islands": { alpha2: "CK", name: "Cook Islands" },
  "costa rica": { alpha2: "CR", name: "Costa Rica" },
  "croatia": { alpha2: "HR", name: "Croatia" },
  "cuba": { alpha2: "CU", name: "Cuba" },
  "curaçao": { alpha2: "CW", name: "Curaçao" },
  "curacao": { alpha2: "CW", name: "Curaçao" },
  "cyprus": { alpha2: "CY", name: "Cyprus" },
  "czechia": { alpha2: "CZ", name: "Czechia" },
  "czech republic": { alpha2: "CZ", name: "Czechia" },
  "côte d'ivoire": { alpha2: "CI", name: "Côte d'Ivoire" },
  "cote d'ivoire": { alpha2: "CI", name: "Côte d'Ivoire" },
  "ivory coast": { alpha2: "CI", name: "Côte d'Ivoire" },
  "denmark": { alpha2: "DK", name: "Denmark" },
  "djibouti": { alpha2: "DJ", name: "Djibouti" },
  "dominica": { alpha2: "DM", name: "Dominica" },
  "dominican republic": { alpha2: "DO", name: "Dominican Republic" },
  "ecuador": { alpha2: "EC", name: "Ecuador" },
  "egypt": { alpha2: "EG", name: "Egypt" },
  "el salvador": { alpha2: "SV", name: "El Salvador" },
  "equatorial guinea": { alpha2: "GQ", name: "Equatorial Guinea" },
  "eritrea": { alpha2: "ER", name: "Eritrea" },
  "estonia": { alpha2: "EE", name: "Estonia" },
  "eswatini": { alpha2: "SZ", name: "Eswatini" },
  "swaziland": { alpha2: "SZ", name: "Eswatini" },
  "ethiopia": { alpha2: "ET", name: "Ethiopia" },
  "falkland islands (malvinas)": { alpha2: "FK", name: "Falkland Islands (Malvinas)" },
  "falkland islands": { alpha2: "FK", name: "Falkland Islands" },
  "faroe islands": { alpha2: "FO", name: "Faroe Islands" },
  "fiji": { alpha2: "FJ", name: "Fiji" },
  "finland": { alpha2: "FI", name: "Finland" },
  "france": { alpha2: "FR", name: "France" },
  "french guiana": { alpha2: "GF", name: "French Guiana" },
  "french polynesia": { alpha2: "PF", name: "French Polynesia" },
  "french southern territories": { alpha2: "TF", name: "French Southern Territories" },
  "gabon": { alpha2: "GA", name: "Gabon" },
  "gambia": { alpha2: "GM", name: "Gambia" },
  "georgia": { alpha2: "GE", name: "Georgia" },
  "germany": { alpha2: "DE", name: "Germany" },
  "ghana": { alpha2: "GH", name: "Ghana" },
  "gibraltar": { alpha2: "GI", name: "Gibraltar" },
  "greece": { alpha2: "GR", name: "Greece" },
  "greenland": { alpha2: "GL", name: "Greenland" },
  "grenada": { alpha2: "GD", name: "Grenada" },
  "guadeloupe": { alpha2: "GP", name: "Guadeloupe" },
  "guam": { alpha2: "GU", name: "Guam" },
  "guatemala": { alpha2: "GT", name: "Guatemala" },
  "guernsey": { alpha2: "GG", name: "Guernsey" },
  "guinea": { alpha2: "GN", name: "Guinea" },
  "guinea-bissau": { alpha2: "GW", name: "Guinea-Bissau" },
  "guyana": { alpha2: "GY", name: "Guyana" },
  "haiti": { alpha2: "HT", name: "Haiti" },
  "heard island and mcdonald islands": { alpha2: "HM", name: "Heard Island and McDonald Islands" },
  "holy see": { alpha2: "VA", name: "Holy See" },
  "vatican city": { alpha2: "VA", name: "Vatican City" },
  "honduras": { alpha2: "HN", name: "Honduras" },
  "hong kong": { alpha2: "HK", name: "Hong Kong" },
  "hungary": { alpha2: "HU", name: "Hungary" },
  "iceland": { alpha2: "IS", name: "Iceland" },
  "india": { alpha2: "IN", name: "India" },
  "indonesia": { alpha2: "ID", name: "Indonesia" },
  "iran": { alpha2: "IR", name: "Iran" },
  "iraq": { alpha2: "IQ", name: "Iraq" },
  "ireland": { alpha2: "IE", name: "Ireland" },
  "isle of man": { alpha2: "IM", name: "Isle of Man" },
  "israel": { alpha2: "IL", name: "Israel" },
  "italy": { alpha2: "IT", name: "Italy" },
  "jamaica": { alpha2: "JM", name: "Jamaica" },
  "japan": { alpha2: "JP", name: "Japan" },
  "jersey": { alpha2: "JE", name: "Jersey" },
  "jordan": { alpha2: "JO", name: "Jordan" },
  "kazakhstan": { alpha2: "KZ", name: "Kazakhstan" },
  "kenya": { alpha2: "KE", name: "Kenya" },
  "kiribati": { alpha2: "KI", name: "Kiribati" },
  "north korea": { alpha2: "KP", name: "North Korea" },
  "south korea": { alpha2: "KR", name: "South Korea" },
  "korea, republic of": { alpha2: "KR", name: "South Korea" },
  "kosovo": { alpha2: "XK", name: "Kosovo" },
  "kuwait": { alpha2: "KW", name: "Kuwait" },
  "kyrgyzstan": { alpha2: "KG", name: "Kyrgyzstan" },
  "laos": { alpha2: "LA", name: "Laos" },
  "latvia": { alpha2: "LV", name: "Latvia" },
  "lebanon": { alpha2: "LB", name: "Lebanon" },
  "lesotho": { alpha2: "LS", name: "Lesotho" },
  "liberia": { alpha2: "LR", name: "Liberia" },
  "libya": { alpha2: "LY", name: "Libya" },
  "liechtenstein": { alpha2: "LI", name: "Liechtenstein" },
  "lithuania": { alpha2: "LT", name: "Lithuania" },
  "luxembourg": { alpha2: "LU", name: "Luxembourg" },
  "macao": { alpha2: "MO", name: "Macao" },
  "macau": { alpha2: "MO", name: "Macao" },
  "madagascar": { alpha2: "MG", name: "Madagascar" },
  "malawi": { alpha2: "MW", name: "Malawi" },
  "malaysia": { alpha2: "MY", name: "Malaysia" },
  "maldives": { alpha2: "MV", name: "Maldives" },
  "mali": { alpha2: "ML", name: "Mali" },
  "malta": { alpha2: "MT", name: "Malta" },
  "marshall islands": { alpha2: "MH", name: "Marshall Islands" },
  "martinique": { alpha2: "MQ", name: "Martinique" },
  "mauritania": { alpha2: "MR", name: "Mauritania" },
  "mauritius": { alpha2: "MU", name: "Mauritius" },
  "mayotte": { alpha2: "YT", name: "Mayotte" },
  "mexico": { alpha2: "MX", name: "Mexico" },
  "micronesia": { alpha2: "FM", name: "Micronesia" },
  "moldova": { alpha2: "MD", name: "Moldova" },
  "monaco": { alpha2: "MC", name: "Monaco" },
  "mongolia": { alpha2: "MN", name: "Mongolia" },
  "montenegro": { alpha2: "ME", name: "Montenegro" },
  "montserrat": { alpha2: "MS", name: "Montserrat" },
  "morocco": { alpha2: "MA", name: "Morocco" },
  "mozambique": { alpha2: "MZ", name: "Mozambique" },
  "myanmar": { alpha2: "MM", name: "Myanmar" },
  "namibia": { alpha2: "NA", name: "Namibia" },
  "nauru": { alpha2: "NR", name: "Nauru" },
  "nepal": { alpha2: "NP", name: "Nepal" },
  "netherlands": { alpha2: "NL", name: "Netherlands" },
  "new caledonia": { alpha2: "NC", name: "New Caledonia" },
  "new zealand": { alpha2: "NZ", name: "New Zealand" },
  "nicaragua": { alpha2: "NI", name: "Nicaragua" },
  "niger": { alpha2: "NE", name: "Niger" },
  "nigeria": { alpha2: "NG", name: "Nigeria" },
  "niue": { alpha2: "NU", name: "Niue" },
  "norfolk island": { alpha2: "NF", name: "Norfolk Island" },
  "north macedonia": { alpha2: "MK", name: "North Macedonia" },
  "macedonia": { alpha2: "MK", name: "North Macedonia" },
  "northern mariana islands": { alpha2: "MP", name: "Northern Mariana Islands" },
  "norway": { alpha2: "NO", name: "Norway" },
  "oman": { alpha2: "OM", name: "Oman" },
  "pakistan": { alpha2: "PK", name: "Pakistan" },
  "palau": { alpha2: "PW", name: "Palau" },
  "palestine": { alpha2: "PS", name: "Palestine" },
  "panama": { alpha2: "PA", name: "Panama" },
  "papua new guinea": { alpha2: "PG", name: "Papua New Guinea" },
  "paraguay": { alpha2: "PY", name: "Paraguay" },
  "peru": { alpha2: "PE", name: "Peru" },
  "philippines": { alpha2: "PH", name: "Philippines" },
  "pitcairn": { alpha2: "PN", name: "Pitcairn" },
  "poland": { alpha2: "PL", name: "Poland" },
  "portugal": { alpha2: "PT", name: "Portugal" },
  "puerto rico": { alpha2: "PR", name: "Puerto Rico" },
  "qatar": { alpha2: "QA", name: "Qatar" },
  "romania": { alpha2: "RO", name: "Romania" },
  "russia": { alpha2: "RU", name: "Russian Federation" },
  "russian federation": { alpha2: "RU", name: "Russian Federation" },
  "rwanda": { alpha2: "RW", name: "Rwanda" },
  "réunion": { alpha2: "RE", name: "Réunion" },
  "reunion": { alpha2: "RE", name: "Réunion" },
  "saint barthélemy": { alpha2: "BL", name: "Saint Barthélemy" },
  "saint barthelemy": { alpha2: "BL", name: "Saint Barthélemy" },
  "saint helena": { alpha2: "SH", name: "Saint Helena" },
  "saint kitts and nevis": { alpha2: "KN", name: "Saint Kitts and Nevis" },
  "saint lucia": { alpha2: "LC", name: "Saint Lucia" },
  "saint martin": { alpha2: "MF", name: "Saint Martin" },
  "saint pierre and miquelon": { alpha2: "PM", name: "Saint Pierre and Miquelon" },
  "saint vincent and the grenadines": { alpha2: "VC", name: "Saint Vincent and the Grenadines" },
  "samoa": { alpha2: "WS", name: "Samoa" },
  "san marino": { alpha2: "SM", name: "San Marino" },
  "sao tome and principe": { alpha2: "ST", name: "Sao Tome and Principe" },
  "saudi arabia": { alpha2: "SA", name: "Saudi Arabia" },
  "senegal": { alpha2: "SN", name: "Senegal" },
  "serbia": { alpha2: "RS", name: "Serbia" },
  "seychelles": { alpha2: "SC", name: "Seychelles" },
  "sierra leone": { alpha2: "SL", name: "Sierra Leone" },
  "singapore": { alpha2: "SG", name: "Singapore" },
  "sint maarten": { alpha2: "SX", name: "Sint Maarten" },
  "slovakia": { alpha2: "SK", name: "Slovakia" },
  "slovenia": { alpha2: "SI", name: "Slovenia" },
  "solomon islands": { alpha2: "SB", name: "Solomon Islands" },
  "somalia": { alpha2: "SO", name: "Somalia" },
  "south africa": { alpha2: "ZA", name: "South Africa" },
  "south georgia and the south sandwich islands": { alpha2: "GS", name: "South Georgia and the South Sandwich Islands" },
  "south sudan": { alpha2: "SS", name: "South Sudan" },
  "spain": { alpha2: "ES", name: "Spain" },
  "sri lanka": { alpha2: "LK", name: "Sri Lanka" },
  "sudan": { alpha2: "SD", name: "Sudan" },
  "suriname": { alpha2: "SR", name: "Suriname" },
  "svalbard and jan mayen": { alpha2: "SJ", name: "Svalbard and Jan Mayen" },
  "sweden": { alpha2: "SE", name: "Sweden" },
  "switzerland": { alpha2: "CH", name: "Switzerland" },
  "syria": { alpha2: "SY", name: "Syria" },
  "syrian arab republic": { alpha2: "SY", name: "Syria" },
  "taiwan": { alpha2: "TW", name: "Taiwan" },
  "tajikistan": { alpha2: "TJ", name: "Tajikistan" },
  "tanzania": { alpha2: "TZ", name: "Tanzania" },
  "thailand": { alpha2: "TH", name: "Thailand" },
  "timor-leste": { alpha2: "TL", name: "Timor-Leste" },
  "togo": { alpha2: "TG", name: "Togo" },
  "tokelau": { alpha2: "TK", name: "Tokelau" },
  "tonga": { alpha2: "TO", name: "Tonga" },
  "trinidad and tobago": { alpha2: "TT", name: "Trinidad and Tobago" },
  "tunisia": { alpha2: "TN", name: "Tunisia" },
  "turkey": { alpha2: "TR", name: "Turkey" },
  "türkiye": { alpha2: "TR", name: "Turkey" },
  "turkmenistan": { alpha2: "TM", name: "Turkmenistan" },
  "turks and caicos islands": { alpha2: "TC", name: "Turks and Caicos Islands" },
  "tuvalu": { alpha2: "TV", name: "Tuvalu" },
  "uganda": { alpha2: "UG", name: "Uganda" },
  "ukraine": { alpha2: "UA", name: "Ukraine" },
  "united arab emirates": { alpha2: "AE", name: "United Arab Emirates" },
  "united kingdom": { alpha2: "GB", name: "United Kingdom" },
  "united states": { alpha2: "US", name: "United States" },
  "united states of america": { alpha2: "US", name: "United States" },
  "uruguay": { alpha2: "UY", name: "Uruguay" },
  "uzbekistan": { alpha2: "UZ", name: "Uzbekistan" },
  "vanuatu": { alpha2: "VU", name: "Vanuatu" },
  "venezuela": { alpha2: "VE", name: "Venezuela" },
  "vietnam": { alpha2: "VN", name: "Vietnam" },
  "viet nam": { alpha2: "VN", name: "Vietnam" },
  "virgin islands (british)": { alpha2: "VG", name: "Virgin Islands (British)" },
  "virgin islands (u.s.)": { alpha2: "VI", name: "Virgin Islands (U.S.)" },
  "wallis and futuna": { alpha2: "WF", name: "Wallis and Futuna" },
  "western sahara": { alpha2: "EH", name: "Western Sahara" },
  "yemen": { alpha2: "YE", name: "Yemen" },
  "zambia": { alpha2: "ZM", name: "Zambia" },
  "zimbabwe": { alpha2: "ZW", name: "Zimbabwe" },
  "åland islands": { alpha2: "AX", name: "Åland Islands" },
  "aland islands": { alpha2: "AX", name: "Åland Islands" }
};
